### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by Matthaiks**

### CODE REVIEW

**Comment by idrassi** [comment]
Thanks!

**Comment by idrassi** [comment]
@Matthaiks 
I'm preparing a new VeraCrypt release and I have add new strings. I cannot publish the changes before release because they are related to security and so I was wondering if you can help translate them:
---
    <entry lang="en" key="MOUNTPOINT_BLOCKED">ERROR: The volume mount point is blocked because it overrides a protected system directory.\n\nPlease choose a different mount point.</entry>
    <entry lang="en" key="MOUNTPOINT_NOTALLOWED">ERROR: The volume mount point is not allowed because it overrides a directory that is part of the PATH environment variable.\n\nPlease choose a different mount point.</entry>
    <entry lang="en" key="INSECURE_MODE">[INSECURE MODE]</entry>
---

I have a done a draft translation using AI:
---
    <entry lang="pl" key="MOUNTPOINT_BLOCKED">BŁĄD: Punkt podłączania wolumenu jest zablokowany, ponieważ nadpisuje chroniony katalog systemowy.\n\nWybierz inny punkt podłączania.</entry>
    <entry lang="pl" key="MOUNTPOINT_NOTALLOWED">BŁĄD: Punkt podłączania wolumenu nie jest dozwolony, ponieważ nadpisuje katalog, który jest częścią zmiennej środowiskowej PATH.\n\nWybierz inny punkt podłączania.</entry>
    <entry lang="pl" key="INSECURE_MODE">[NIEBEZPIECZNY TRYB]</entry>
---

Thank you in advance for your help.

**Comment by Matthaiks** [comment]
The draft looks fine. I would go with `[TRYB NIEBEZPIECZNY]` instead of `[NIEBEZPIECZNY TRYB]`, though.

**Comment by idrassi** [comment]
Thank you of the prompt reply and the review, I appreciate.
Ok for [TRYB NIEBEZPIECZNY], I will use it.

**Pull request merged**
