### PR TITLE
Add Norwegian Bokmål translation

### PR DESCRIPTION
**Pull request by sandakersmann**
Add Norwegian Bokmål translation

### CODE REVIEW

**Comment by sandakersmann** [comment]
@idrassi This is translated with [https://nano-gpt.com](https://nano-gpt.com) GPT 4o. So some fixes needed, but I think it's a good start :)

**Comment by idrassi** [comment]
Thank you for this contribution. This is a good use of AI. It must have taken you a lot of prompts to achieve this result.
For sure, we need a human feedback/review but it is better than not having any translation.

**Comment by lollolong** [comment]
Hi @sandakersmann & @idrassi , this PR seems to break windows compilation because the resource entry for `IDR_LANG_NB` isn't properly set up.
`error C2065: 'IDR_LANG_NB' : undeclared identifier`

**Comment by sandakersmann** [comment]
I will fix it.

**Comment by sandakersmann** [comment]
This should fix the issue: https://github.com/veracrypt/VeraCrypt/pull/1388

**Comment by idrassi** [comment]
Thank you @lollolong for spotting this.
@sandakersmann PR has been merged.

**Pull request merged**
