### PR TITLE
Add Hausa translation

### PR DESCRIPTION
**Pull request by sandakersmann**
Translated with ChatGPT-4o

### CODE REVIEW

**Comment by idrassi** [comment]
I wasn't familiar with the Hausa language before. I checked, and since it is supported by Windows as a language pack, it makes sense to add it to VeraCrypt.
Thank you for your contribution!

**Comment by idrassi** [comment]
@Jertzukka Indeed, you are making a good point. Shipping translations that are no vetted by native speakers is not good, specially for languages where the AI has little training data like for Hausa. The "VerraCrypt" issue is warning that I should have noticed and I was too quick into merging this. Thank you for your vigilance. 

I will revert this commit which clearly lacks quality.

**Comment by sandakersmann** [comment]
I know a guy that does translations into Hausa. I was going to ask him to look through it after it was merged.

**Comment by idrassi** [comment]
Thank you for the feedback. A human review will be welcome alongside fixing the obvious issues. We can reintroduce the Hausa translation once minimal quality is ensured.

**Pull request merged**
