### PR TITLE
Revise some cursed translations

### PR DESCRIPTION
**Pull request by 0x00000FF**
I saw some strings are translated in somehow cursed way, this need to be fixed.

and I think there are lots of things to be fixed.

Where can I see the english language pack for the reference?

### CODE REVIEW

**Comment by Jertzukka** [comment]
You can find the default English translation strings here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/Language.xml

Often single or couple of words in the translation string isn't enough to accertain what it means in the correct context, so it will help if you use the software and see where and how the translation is used in the program.

**Comment by 0x00000FF** [comment]
Alright, seems fine for now... as a korean. 

Maybe this PR must be integrated with #1291, he did very good work.

**Comment by idrassi** [comment]
@0x00000FF I have merged https://github.com/veracrypt/VeraCrypt/pull/1291 and so there is conflict with three entries in your PR (ASK_NONSYS_INPLACE_ENC_NOTIFICATION_REMOVAL, KEEP_PROMPTING_ME, DO_NOT_PROMPT_ME). 

can you please remove the changes of these entries from your PR so that I can merge it.

Thank you for your contribution.

**Comment by 0x00000FF** [comment]
Well, It seems fine to close this PR because #1291 has been merged. Thank you!

**Comment by idrassi** [comment]
You PR contained translations enhancements that were not covered by #1291. So, I have taken the liberty to push a commit containing your enhancements and of course I gave you credit in the commit message: https://github.com/veracrypt/VeraCrypt/commit/6d37bd662e0847415a366e5af2222f8a3a944807

Thank you again for your contribution.

**Pull request closed without merging**
