### PR TITLE
Update Language.zh-cn.xml

### PR DESCRIPTION
**Pull request by Zhangjintao**
Update Simplified Chinese translation.

### CODE REVIEW

**Comment by idrassi** [comment]
Thank you but there is a small mistake: At line 1392, the field "en-name" must not be changed to "zh-cn-name" because it reflects the XML attribute "en-name" present in the header of the file and which identifies the english name of the current language.

Also, there are two fields whose "lang" attribute was changed to "zh-cn" but which were not translated:
- IDC_SHOW_PIM at line 67
- AUTODETECTION at line 827

if these fields can't be translated, then there "lang" attribute should remain "en".

Once these modifications done, I'll commit your pull request.

**Comment by Zhangjintao** [comment]
Thank your correction, I will fix it later.

**Comment by Zhangjintao** [comment]
I have fixed the mistakes.

**Comment by idrassi** [comment]
Thanks. Pull merged.

**Pull request merged**
