### PR TITLE
Documentation: Update QR codes and logos

### PR DESCRIPTION
**Pull request by sandakersmann**
Used this website to generate the QR codes: https://mini-qr-code-generator.vercel.app

### CODE REVIEW

**Comment by idrassi** [comment]
@sandakersmann: Thank you for this contribution. However, the 300x300 size seems too large for my preference. Could you explain why you chose such a large size?

**Comment by sandakersmann** [comment]
I went with 300x300 so it would be easier to scan. Especially Monero since it contains a lot of data.

**Comment by idrassi** [comment]
@sandakersmann  Yes, please. 200x200 is a good compromise. Thank you.

**Comment by sandakersmann** [comment]
@idrassi QR codes in 200x200 added now :)

**Comment by idrassi** [comment]
Thank you, looks good now!

**Comment by sandakersmann** [comment]
@idrassi You should consider taking Zcash as well for totally private donations. I can make a QR code for Zcash too :)

**Pull request merged**
