### PR TITLE
Language Translations files: update Chinese (Hong Kong) translation

### PR DESCRIPTION
**Pull request by harryytm**
- replace Mainland China terminologies with Hong Kong terminologies
- switch to Windows default Chinese Traditional fonts
- correct lang attribute on untranslated entries to en
- correct mismatch translations in lines 635-640
- correct size unit to KiB, MiB, GiB, TiB
- add back and translated missing line 298
- refine wordings

### CODE REVIEW

**Comment by harryytm** [comment]
@idrassi I will keep working on it on 22JUL, please merge this pull on last minute of merge window, thanks.

**Comment by harryytm** [comment]
@idrassi resolved conflict to allow merge

**Comment by idrassi** [comment]
Thank you for the update and conflict fix.
I had an issue during testing and so I could not release 1.26.4 version. I will try to release it today.

**Comment by idrassi** [comment]
I will merge your PR now to prepare for the release.
Thank you for your efforts!

**Pull request merged**
