### PR TITLE
[Success] Update Language.ko.xml

### PR DESCRIPTION
**Pull request by Kieaer**
Too many wrong typos and untranslated.
1400 lines 😭

### CODE REVIEW

**Comment by idrassi** [comment]
Thank you for this effort. It’s much needed!
Are you going to push more changes? I’m asking to know if I merge this now or later.

**Comment by Kieaer** [comment]
I think it will take about two weeks.

**Comment by Kieaer** [comment]
Note
https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/Language.xml

**Comment by Kieaer** [comment]
Default translation completed
Start examination

**Comment by GH-Rake** [comment]
Thank you for contributing to this project!

**Comment by Kieaer** [comment]
I'm busy so I can't do it quickly.
I'll finish it one day, so wait :smile:

**Comment by Kieaer** [comment]
@idrassi

**Comment by idrassi** [comment]
Thank you for this huge work. I have merge your translation.

**Comment by idrassi** [comment]
@Kieaer I have received a new Korean translation that apparently is better but I would like to have your feedback on it. I'm attaching it here.
Can you please check it and give your feedback? Thank you for your help.

[Language.ko.xml.zip](https://github.com/veracrypt/VeraCrypt/files/3941978/Language.ko.xml.zip)

**Comment by Kieaer** [comment]
@idrassi No no. Who make this translate
Too many translations that don't fit the program.

**Pull request merged**
