### PR TITLE
Adding more Turkish translations

### PR DESCRIPTION
**Pull request by ozgurpek**
This change is translating some still English lines to Turkish

### CODE REVIEW

**Comment by ozgurpek** [comment]
Hi,

I am a native Turkish speaker, and would like to contribute to this project initially with translations, then, if possible, with small contributions on the code

**Comment by andreas-becker** [comment]
Hey @ozgurpek thank you for your contribution. It is always good to have a native speaker updating translations.

@idrassi i did quickly re-check the translations and they look good to me.

**Comment by ozgurpek** [comment]
@andreas-becker 

no problem at all, i will try to translate rest of the file by time. It is just too big to do in a single pass :)

**Comment by idrassi** [comment]
@ozgurpek Thank you for your contribution.

**Pull request merged**
