### PR TITLE
fix Program freeze Volume Creation Wizard linux

### PR DESCRIPTION
**Pull request by T-Bonhagen**
fix for #724

### CODE REVIEW

**Comment by thewh1teagle** [comment]
Did you tested your fix? 
Because I tried your fix, and for me it didn't fixed.

**Comment by T-Bonhagen** [comment]
@thewh1teagle 
Yes, it is working
Screenshot_20210113_083344
Screenshot_20210113_083322

**Comment by T-Bonhagen** [comment]
@thewh1teagle 
Please provide you env LANG so i can test.
I've test with "LANG=", LANG=en, LANG=de_DE.UTF-8 sucessfully.

**Comment by thewh1teagle** [comment]
@T-Bonhagen 
Sorry i was mistake it works with your fork.
the problem happens when I use [my translation file](https://github.com/thewh1teagle/VeraCrypt/blob/master/Translations/Language.he.xml).
env LANG is `en_US.UTF-8`
Linux distro is `ubuntu 20.10`
My compile steps  is [here](https://gist.github.com/thewh1teagle/7b76aadac365b102f8435823976e306b)

**Comment by T-Bonhagen** [comment]
Looks like you found a bug in wxString::Replace with your LANG=he

**Comment by thewh1teagle** [comment]
@T-Bonhagen 
How do you debug veracrypt? Maybe I can try to fix it

**Comment by T-Bonhagen** [comment]
with kdevelop 
build with "make  DEBUGGER=1"
Looks like it is related to the change of text orientation for he and back to en in the sentence. 
e.g.  in TWO_LAYER_CASCADE_HELP

**Comment by thewh1teagle** [comment]
@T-Bonhagen 
I tried with `make DEBUGGER=1 WXSTATIC=1 WITHGTK3=1 -j$(nproc --all)` but I don't see debug messages when I start the program

**Comment by T-Bonhagen** [comment]
Looks like there is also a error in your xml in THREE_LAYER_CASCADE_HELP
the %d is not ok.
I

**Comment by T-Bonhagen** [comment]
DEBUGGER=1 is for debug symbols so you can attach a debugger

**Comment by T-Bonhagen** [comment]
fixed xml
[Language.he.zip](https://github.com/veracrypt/VeraCrypt/files/5808833/Language.he.zip)

**Comment by thewh1teagle** [comment]
@T-Bonhagen 
Good catch!
The problem was because error in xml in `THREE_LAYER_CASCADE_HELP`
Thank you very much for the help and for the fixes

**Comment by andreas-becker** [comment]
It's so good to see, that you guys filed a bug and fixed it together! Props ;-)

**Comment by idrassi** [comment]
Thank you for the fix and sorry for the late merge, past weeks have not been easy.

**Pull request merged**
