### PR TITLE
Use XDG_CONFIG_HOME to determine the path of the configuration

### PR DESCRIPTION
**Pull request by davidfoerster**
Adhere to the [XDG Desktop Specification] and use the environment variable `XDG_CONFIG_HOME` to determine location of configuration files on *all* platforms. If it is unset or empty resort to platform-specific defaults.
    
On Windows and OS X, `wxStandardPaths` provides correct defaults (equal to the previous hard-coded paths) but on Linux and other Unices `~/.config/appinfo` would be better than `~/.appinfo`. This means we treat those platforms as a special case. It also means that we may need to fall back to the legacy location if it exists but the new location doesn't.

Unfortunately I have no way to test this on OS X or Windows, though the algorithm and code for these platforms are much more straightforward than on Linux.

See issue #53.

  [XDG Desktop Specification]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

### CODE REVIEW

**Comment by idrassi** [comment]
Thank you for your contribution.
I agree with the changes but we need extra code handle existing configuration files: for users who are already using VeraCrypt, deploying this change will result for them losing there favorites list and their various other configurations.

An idea would to keep the original code in a method (for example `Application::GetConfigFileLegacyPath`) and in the new implementation we will look if the requested file already exists in the legacy path and if yes we will move it to the new XDG path before returning from the function.

Can you implement this extra logic in your patch? it is the only missing thing in order to merge this pull request.

Thank you again for your help.

**Comment by davidfoerster** [comment]
> An idea would to keep the original code in a method (for example `Application::GetConfigFileLegacyPath`) and in the new implementation we will look if the requested file already exists in the legacy path and if yes we will move it to the new XDG path before returning from the function.

I already implemented [something very similar](/davidfoerster/VeraCrypt/blob/xdg-config-paths/src/Main/Application.cpp#L56) but it's not very obvious since the changes only affect Linux and BSD users. The paths on Windows and OS X stay the same unless the user runs VeraCrypt with `XDG_CONFIG_HOME` set to something different than `%APPDATA%` (Windows) or `$HOME/Library/Application Support` (OS X).

Let me know if you have suggestions for a different behaviour for the look-up of legacy configuration paths or  would like some refactoring.

**Comment by idrassi** [comment]
Indeed, I missed this part.
My idea was to migrate the file from the legacy path to the standard path. I see that your approach is more prudent in that it simply points to the existing file. This is acceptable for me.

One remark about the static pointer configDirC: what about replacing it with a wxScopedPtr<wxString*>? It will be much cleaner than using a static pointer.

**Comment by davidfoerster** [comment]
> One remark about the static pointer configDirC: what about replacing it with a `wxScopedPtr<wxString*>`? It will be much cleaner than using a static pointer.

I can do that if you want to. I'm not sure if it'll do much good though. At least a few years ago neither C++03 nor the documentation of most C++ compilers were clear when the destructors of static values are called; so the recommendation for static values was to just use a pointer to a heap-allocated object instead of the object itself – at least that way it would be clear that they are never destroyed unless explicitly requested by the programmer.

While looking for a source I found https://stackoverflow.com/a/2204628/2461638, so I'm going to go with your suggestion of a scoped pointer.

**Comment by idrassi** [comment]
Thanks!

**Pull request merged**
