### PR TITLE
Add information about the translation process

### PR DESCRIPTION
**Pull request by sandakersmann**
Add information about the translation process

### CODE REVIEW

**Comment by nkh0472** [comment]
Is the platform in this commit officially supported @idrassi? If so, this information also should be added to the [documents](https://veracrypt.fr/en/Documentation.html) and [FAQs](https://veracrypt.fr/en/FAQ.html).

**Comment by idrassi** [comment]
@nkh0472 @sandakersmann 
I did open a Transifex account for VeraCrypt many years ago to facilitate translations. However, I found it to be very time-consuming, especially when it came to converting translations from the Transifex format to VeraCrypt's XML format. Merging changes line by line was particularly challenging. It is not feasible to simply export files from Transifex and overwrite VeraCrypt's existing ones.

Given these challenges, I opted to **stop** using Transifex. I currently rely solely on GitHub PRs for translations as they are straightforward to merge and significantly less time-consuming for me to manage.

Considering this, the Transifex link should not be added to the README or any other official documentation, as it might confuse contributors. It would be best to close the Transifex page related to VeraCrypt. I simply cannot dedicate the necessary time to manage and convert translations from there.

However, if there's someone from the community willing to dedicate their time to regularly create PRs based on Transifex updates, that would indeed be beneficial. I just want to clarify that I personally cannot take on that task anymore.

Thank you for your efforts and understanding.

**Comment by sandakersmann** [comment]
Thanks for clarifying and all the great work you do :)

**Comment by Patriccollu** [comment]
@idrassi 
In addition to the [Transifex](https://explore.transifex.com/otf/veracrypt/) page, there is also a [Crowdin](https://crowdin.com/project/veracrypt) project for **VeraCrypt** but the latest activity was 7 years ago!

**Comment by jermanuts** [comment]
Hello @idrassi have you looked into https://weblate.org/en/?

@comradekingu might tell if Weblate support and simplify this process.

For the time being, I think docs should be updated so translators can actually contribute by opening PRs on Github than using Transifex.

**Pull request closed without merging**
